/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Instrument_Cluster_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_Instrument_Cluster_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/InstrumentClusterStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {

/**
 * Provides a default implementation for InstrumentClusterStubRemoteEvent and
 * InstrumentClusterStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT InstrumentClusterStubDefault
    : public virtual InstrumentClusterStub {
public:
    COMMONAPI_EXPORT InstrumentClusterStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(InstrumentCluster::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT InstrumentClusterStubRemoteEvent* initStubAdapter(const std::shared_ptr< InstrumentClusterStubAdapter> &_adapter) {
        CommonAPI::Stub<InstrumentClusterStubAdapter, InstrumentClusterStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void setSpeedRpm(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _SensorRpm, setSpeedRpmReply_t _reply) {
        (void)_client;
        (void)_SensorRpm;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setBattery(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _Battery, setBatteryReply_t _reply) {
        (void)_client;
        (void)_Battery;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setGear(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _Gear, setGearReply_t _reply) {
        (void)_client;
        (void)_Gear;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setDirection(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _Direction, setDirectionReply_t _reply) {
        (void)_client;
        (void)_Direction;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setLight(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _light, setLightReply_t _reply) {
        (void)_client;
        (void)_light;
        std::string message = "";
        _reply(message);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual InstrumentClusterStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(InstrumentClusterStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        InstrumentClusterStubDefault *defaultStub_;
    };
protected:
    InstrumentClusterStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_Instrument_Cluster_STUB_DEFAULT
